<template>
  <div>
    <label class="block text-sm font-display text-ink-2 mb-1">{{ label }}</label>

    <!-- Single mode: one chosen customer shown as a pill with a change action,
         no room for ambiguity about which value the field actually holds. -->
    <div v-if="!multiple && selected.length" class="flex items-center justify-between rounded-xl border border-rule bg-surface px-3 py-2 text-sm">
      <span>{{ labels[selected[0]] || selected[0] }}</span>
      <button type="button" class="text-xs text-accent-ink font-display font-medium" @click="remove(selected[0])">Change</button>
    </div>

    <div v-if="multiple && selected.length" class="flex flex-wrap gap-1.5 mb-1.5">
      <span
        v-for="name in selected"
        :key="name"
        class="inline-flex items-center gap-1 rounded-full bg-accent-soft text-accent-ink text-xs font-display px-2.5 py-1"
      >
        {{ labels[name] || name }}
        <button type="button" class="leading-none" @click="remove(name)">&times;</button>
      </span>
    </div>

    <div v-if="multiple || !selected.length" class="relative">
      <input
        v-model="query"
        type="text"
        placeholder="Search customer…"
        class="w-full rounded-xl border border-rule bg-surface px-3 py-2 text-sm"
        @input="onInput"
        @focus="onInput"
      />
      <div
        v-if="results.length"
        class="absolute z-10 mt-1 w-full max-h-48 overflow-y-auto rounded-xl border border-rule bg-surface shadow-lg"
      >
        <button
          v-for="r in results"
          :key="r.name"
          type="button"
          class="block w-full text-left px-3 py-2 text-sm hover:bg-ground"
          @click="add(r)"
        >
          {{ r.customer_name || r.name }}
        </button>
      </div>
    </div>
  </div>
</template>

<script setup>
// Customer picker, two modes:
// - multiple (default): comma-joined-string storage, matching Flutter's exact
//   wire format for field_sales.api.journey_plan's primary/secondary_customer.
// - single (multiple=false): plain single Customer name, e.g. Field Visit's
//   `customer` Link field - one chosen value shown as a pill, "Change" to
//   search again, rather than a raw text box the rep has to type exactly.
import { reactive, ref, watch } from "vue"
import { call } from "frappe-ui"

const props = defineProps({
  label: { type: String, default: "Customer(s)" },
  modelValue: { type: String, default: "" },
  multiple: { type: Boolean, default: true },
  // Scopes search to distributor-level customers (Customer.is_dl=1) - the
  // only customers the org's own master data allows as a channel partner.
  distributorsOnly: { type: Boolean, default: false },
  // Scopes search to Secondary-level customers (Customer.customer_level ==
  // "Secondary") - the only customers a channel partner order applies to,
  // since a Secondary customer's channel partner is fixed on its own record.
  secondaryOnly: { type: Boolean, default: false },
  // Any other real filter_fields customer_list/distributor_list already
  // declare (e.g. { custom_channel_partner: "..." } to narrow to one
  // channel partner's own Secondary customers) - passed straight through.
  extraFilters: { type: Object, default: () => ({}) },
  // A friendly label for the current modelValue, known up front by the
  // caller (e.g. a visit-conversion prefill setting the picked customer
  // externally, never through this component's own add()/search flow) - so
  // the picked-state pill doesn't show the raw Customer id until a search
  // happens to populate the real labels map.
  knownLabel: { type: String, default: "" },
})
const emit = defineEmits(["update:modelValue"])

const selected = ref(splitNames(props.modelValue))
const query = ref("")
const results = ref([])
// name -> customer_name, filled in whenever a result list loads or a pick is
// made - the picked-state display shows the friendly label, not the raw
// Customer id, which for most real customers is an autogenerated code.
const labels = reactive({})
if (props.modelValue && props.knownLabel) labels[props.modelValue] = props.knownLabel
watch(
  () => [props.modelValue, props.knownLabel],
  ([v, label]) => {
    if (v && label) labels[v] = label
  }
)
let debounceTimer = null

watch(
  () => props.modelValue,
  (v) => {
    const names = splitNames(v)
    if (names.join(",") !== selected.value.join(",")) selected.value = names
  }
)

function splitNames(v) {
  if (!v) return []
  if (!props.multiple) return [v]
  return v
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean)
}

function emitValue() {
  emit("update:modelValue", props.multiple ? selected.value.join(", ") : selected.value[0] || "")
}

function add(record) {
  const name = record.name
  labels[name] = record.customer_name || name
  if (props.multiple) {
    if (!selected.value.includes(name)) selected.value.push(name)
  } else {
    selected.value = [name]
  }
  emitValue()
  query.value = ""
  results.value = []
}

function remove(name) {
  selected.value = selected.value.filter((n) => n !== name)
  emitValue()
}

// Loads a default (unfiltered) page of options - used both on focus, before
// the rep has typed anything, and whenever the query is cleared back to
// empty. Without this, opening the field showed nothing until you typed a
// character, which read as broken rather than as a search box.
function pickerMethod() {
  return props.distributorsOnly
    ? "field_sales.api.customers.distributor_list"
    : "field_sales.api.customers.customer_list"
}

function pickerArgs(extra) {
  const args = { ...extra, ...props.extraFilters }
  if (props.secondaryOnly) args.customer_level = "Secondary"
  return args
}

function rememberLabels(records) {
  for (const r of records) labels[r.name] = r.customer_name || r.name
}

async function loadDefault() {
  try {
    const page = await call(pickerMethod(), pickerArgs({ limit: 8, current_page: 1 }))
    const records = page?.records || []
    rememberLabels(records)
    results.value = records.filter((r) => !selected.value.includes(r.name))
  } catch {
    results.value = []
  }
}

function onInput() {
  clearTimeout(debounceTimer)
  const text = query.value.trim()
  if (!text) {
    loadDefault()
    return
  }
  debounceTimer = setTimeout(async () => {
    try {
      const page = await call(pickerMethod(), pickerArgs({ search_text: text, limit: 8, current_page: 1 }))
      const records = page?.records || []
      rememberLabels(records)
      results.value = records.filter((r) => !selected.value.includes(r.name))
    } catch {
      results.value = []
    }
  }, 250)
}
</script>
